#!/usr/bin/env python
# coding: utf-8

# # SED Processing of CIGALE SED Decomposition fits
# This script is used to explore and proccess some of the outputs from the fits files generated by the CIGALE SED decomposition. We intend for this to explore the AGN contribution with a more robust set of tools to see how AGN contamination effects UVJ and other diagnostics.

# In[95]:


# Import all required packages
import matplotlib.pyplot as plt
import astropy.units as u
import numpy as np
import pandas as pd
import os
from astLib import astSED
import astropy.io.fits as fits
from carf import * # custom module for functions relating to the project
import matplotlib.path as mpath
import seaborn as sns

# refresh

# So that we can change the helper functions without reloading the kernel
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('autoreload', '2')


# In[96]:


# The aim of this is to see how the SEDs of the galaxies are
# to this end what we do is read in some of the fits files
# Begin by importing just one of the fits files
gal_name= '9367_best_model.fits'
galaxy_path = os.path.join('datasets\student_fits_files\cdfs_best_models_fits', gal_name)
    
# Open the fits files <- needs to be different for CAT vs Fits files
with fits.open(galaxy_path) as data:
    df = pd.DataFrame(np.array(data[1].data).byteswap().newbyteorder())


# In[97]:


# Filters
pb_U_path = os.path.join('datasets', 'Filters', 'Generic_Johnson.U.dat')
pb_V_path = os.path.join('datasets', 'Filters', 'Generic_Johnson.V.dat')
pb_J_path = os.path.join('datasets', 'Filters', '2MASS_2MASS.J.dat')


pb_U = astSED.Passband(pb_U_path, normalise=False)
pb_V = astSED.Passband(pb_V_path, normalise=False)
pb_J = astSED.Passband(pb_J_path, normalise=False)


# In[98]:


df # We recall wavelength is in nanometers, we would like to immediately convert this to angstroms




df['wavelength'] = df['wavelength']*10

# For plotting reasons, convert to Janksys
# We are already in mJanksys
df['Snu'] = df['Fnu']*10**-3

# Converting into F_lambda
df['Flambda'] = df['Snu']*(3*10**-5)/(df['wavelength']**2)


# In[99]:


df


# In[100]:



# Only plot between 10^3 and 10^5

# Do a logplot of the lines 
plt.figure(figsize=(10, 6))
plt.loglog(df['wavelength'], df['Flambda'], label='Flux')
plt.xlabel('Wavelength (Angstroms)')
plt.ylabel('Flux (Fnu)')
# Change the limits from 10^3 to 10^5


#plt.ylim(1e-2, 1e2)


plt.title('SED of galaxy')
plt.legend()
plt.show()


# In[101]:


# We can see that this kind of works. What we would now like to do, is extend this idea to a few more galaxies. Instead
# of one. We can read in say n number of galaxies, convert to what we use and then plot them all together
# We will be able to see that these galaxies are not restframed, we need to use the exported zpk from a previous file 
# to restframe them.

# Reading in the file containing the id's plus, filed, plus redshift
queiscent_transitions = pd.read_csv('outputs\quiescent_transition_ids.csv')


# In[102]:


queiscent_transitions

# we can use something like this
# wavelengths = wavelengths / (1 + float(selected_redshifts[z_id]))


# In[103]:



def get_n_seds(df, n, restframe=False, all=False):
    # Select n galaxies
    
    df_list = []
    names = []
    redshifts = []
    if all==False:
        selected_galaxies = df.sample(n)
    else: 
        selected_galaxies = df
        
    # Reset the index
    selected_galaxies = selected_galaxies.reset_index(drop=True)
    
    # name 
    gal_name = selected_galaxies['id'].astype(str)
    
    # field
    gal_field = selected_galaxies['field'].astype(str)
    
    
    names = gal_field + '_' + gal_name
    gal_redshift = selected_galaxies['zpk'].astype(float)

    # Now we will read in the fits files for these galaxies

    for i in range(len(selected_galaxies)):
        path = 'datasets\student_fits_files\\'+ str(gal_field[i]).lower() +'_best_models_fits\\'
        name = str(gal_name[i])+'_best_model.fits'

        galaxy_path = os.path.join(path, name)
        with fits.open(galaxy_path) as data:
            df = pd.DataFrame(np.array(data[1].data).byteswap().newbyteorder())
        
        # Convert to angstroms
        df['wavelength'] = df['wavelength']*10

        if restframe:
            df['Snu'] = df['Fnu']*10**-3 # milliJanksys to Janksys <- J = ergs/(s*(cm^2)*(s^-1))
            # F_nu currently has a frequency dependence, convert to nuFnu by multiplying the the frequency associated
            # with the wavelength, as we are in angstroms, we can use the formula c = f*lambda
            
            
            # This should prevent any issues, but check
            freq = (3*10**18)/df['wavelength'] # in Hz
            # multiply the Snu * nu to get nuSnu
            df['nuSnu'] = df['Snu']*freq
            # Restframe the values of wavelength
            df['wavelength'] = df['wavelength'] / (1 + gal_redshift[i]) # we redshift the values of of wavelength
            # now calculate a new frequency, based on the new wavelength
            freq = (3*10**18)/df['wavelength'] # in Hz
            # divide the nuSnu by the new frequency to get the restframed values
            df['Snu'] = df['nuSnu']/freq
            
            # Convert flux values
            df['Flambda'] = df['Snu']*(3*10**-5)/(df['wavelength']**2) # S_nu to F_lambda <- angstroms 
            
        else:
            # Convert flux values
            df['Snu'] = df['Fnu']*10**-3 # milliJanksys to Janksys <- J = ergs/(s*(cm^2)*(s^-1))
            df['Flambda'] = df['Snu']*(3*10**-5)/(df['wavelength']**2) # S_nu to F_lambda <- angstroms 
            
        
            
            
        redshift_Val = gal_redshift[i]
        redshifts.append(redshift_Val)        
        
        

        
        # For simplicity, just create some extra columns
        df['lambda (Angstroms)'] = df['wavelength']
        df['Total Flux (erg/s/cm^2/Angstrom)'] = df['Flambda']
        
        
        
        df_list.append(df)
        
        
        plt.loglog(df['wavelength'], df['Flambda'])
    plt.xlabel('Wavelength (Angstroms)')
    plt.ylabel('Flux (Fnu)')
    #plt.xlim(1e3, 1e5)
    plt.ylim(1e-30, 1e-2)
    plt.title('SED of galaxies')
    plt.legend()
    plt.show()
    
    print(len(df_list))
    
    return df_list, names, redshifts


# In[104]:


#get_n_seds(100, restframe=True)


# We can see by using this code that we can read in the 'best fit' models of these SEDS and rest frame them using their zpk value. Now we can extend this code as required

# In[105]:


best_fit_seds, names, redshifts = get_n_seds(100, restframe=True, all=True)


# In[ ]:





# In[106]:


# we will use astSED to generate the colours right here


# In[107]:


len(best_fit_seds)


# In[108]:


len(names)
#names


# In[109]:


# For simplicity, for each of the names, have a dictionary entry with the associated dataframe
# This will make it easier to access the dataframes
# We will also convert the names to a list
names = names.tolist()


# In[110]:


# names

# # setting up the dictionary
# best_fit_seds_dict = dict(zip(names, best_fit_seds))


# In[111]:


# best_fit_seds_dict


# In[112]:


# Seperately we would like to just acces best_fit_seds
# best_fit_seds


# In[113]:


# Lets just explore the first restframed galaxy with everything plotted
sed_0 = best_fit_seds[0]


plt.figure(figsize=(10, 6))
plt.loglog(sed_0['wavelength'], sed_0['L_lambda_total'], label='')
plt.xlabel('Wavelength (Angstroms)')
plt.ylabel('L_lambda_total (W nm^-1)')
#plt.ylim(1e-30, 1e-2)
plt.title('SED of galaxy')
plt.show()


# Happily we see the best fit SEDS are correct in terms of their restframed shape and position. This means that these SEDS can therefore be used. But this is not all as we also need to explore the other ontributions
# which are shown in the dataframe
# best_fit_seds

# In[114]:


# we are going to try and plot the SEDs to see the differences, and export an ID, and UVJ colours (recalling UVJ are inherently restframed)
# We will use a similar techinques as previous scripts have done
# Using our previous technique


# Get one de-redshifted template
# We will use the selection of them
best_fit_seds


# In[115]:


# Now we would like to, for each of the templates calculate a colour
# -  now we can go and have a look, creating colours are required

best_fit_seds[0]


# In[116]:


# for each of the entries, we will create a list of the ID, and the UVJ colours, remembering these are rest framed

export_df = pd.DataFrame(columns=['ID', 'UV', 'VJ'])


# In[117]:


export_df


# In[118]:


# Create the colours cigale outputs
best_fit_seds[0]


# In[119]:


# try using the composite colours function 
# for each value in best fit seds, make an output in a list

best_fits = [x for x in best_fit_seds]


# In[120]:



uv_0, vj_0 = generate_UVJ_composite_set_colours([best_fit_seds], [0], pb_U, pb_V, pb_J)


# In[121]:


uv_0
vj_0


# In[122]:


# now we can add this to the df


# In[123]:


names


# In[124]:


uv = uv_0[0]
vj = vj_0[0]


# In[125]:


# Now we have our id's, our UV and VJ values, we can fully export this to a csv file
# adding all UVJ colours into the dataframe
export_df['ID'] = names
export_df['UV'] = uv
export_df['VJ'] = vj
export_df['zpk'] = redshifts


# In[126]:


export_df


# In[127]:


# We can attempt to plot this UVJ diagram, recalling that we are hopefully going to be seeing only values in the quiescent region

def plot_uvj_nocategorise(df, x, y):
    plt.figure(figsize=(6, 6))

    xmax = 2.2
    ymax = 2.5
    xmin = -0.5
    ymin = 0

    # Set the plotting limits
    plt.xlim(xmin, xmax)
    plt.ylim(ymin, ymax)

    # Define the points for a quiescent galaxy selection
    x_points = [-0.5, 0.85, 1.6, 1.6]
    y_points = [1.3, 1.3, 1.95, 2.5]

    # Plot the points
    plt.plot(x_points, y_points, linestyle='-')

    # as all the points have associated names, plot the names
    #for i, txt in enumerate(df['ID']):
    #    plt.annotate(txt, (x[i], y[i]))
        


    # Interpolate the y-value at x=1.2
    x_target = 1.2
    y_target = np.interp(x_target, x_points, y_points)

    # Plot the interpolated point, this separates everything on the right as dusty galaxies,
    # and everything on the left as star-forming galaxies
    plt.plot([x_target, x_target], [0, y_target], linestyle='--')

    quiescent_x = [-0.5, 0.85, 1.6, 1.6, xmin, xmin]
    quiescent_y = [1.3, 1.3, 1.95, 2.5, ymax, 1.3]
    # We want to make a wedge selection for the Quiescent Selection of Galaxies
    points = np.column_stack([x, y])
    verts = np.array([quiescent_x, quiescent_y]).T
    path = mpath.Path(verts)


    # Define the path for point selection
    #selected_path = mpath.Path([(2, 3), (6, 4), (8, 2), (2, 1), (2, 3)])  # Example path, replace with your own

    # Use path.contains_points to get a boolean array
    points_inside_selection = path.contains_points(np.column_stack([x, y]))



    dusty_condition = (points[:, 0] > x_target) & (~points_inside_selection)
    star_forming_condition = (points[:, 0] < x_target) & (~points_inside_selection)



    # Filter the DataFrame using the boolean array
    selected_df = df[points_inside_selection] # For quiescent, clean later



    # Sort the quiescent and non-quiescent galaxies
    quiescent_points = points[path.contains_points(points)]
    # Find the points from here to categorise dusty, and star-forming galaxies
    non_quiescent_points = points[~path.contains_points(points)]
    dusty_galaxies_points = non_quiescent_points[non_quiescent_points[:, 0] > x_target]
    star_forming_galaxies_points = non_quiescent_points[non_quiescent_points[:, 0] < x_target]



    # print the number of galaxies that are in each category
    print(f'Number of Quiescent Galaxies: {len(quiescent_points)}')
    print(f'Number of Dusty Galaxies: {len(dusty_galaxies_points)}')
    print(f'Number of Star Forming Galaxies: {len(star_forming_galaxies_points)}')
    
    #print(non_quiescent_points[0][0])

    #print(y)
    # Plot the selected points
    #plt.scatter(x, y, s=3, alpha=0.5, label='Not Quiescent Selection')
    plt.scatter(quiescent_points[:, 0], quiescent_points[:, 1], c='r', s=3, alpha=0.5, label='Quiescent Selection')
    plt.scatter(dusty_galaxies_points[:, 0], dusty_galaxies_points[:, 1], c='g', s=3, alpha=0.5, label='Dusty Galaxies')
    plt.scatter(star_forming_galaxies_points[:, 0], star_forming_galaxies_points[:, 1], c='b', s=3, alpha=0.5, label='Star Forming Galaxies')

    plt.xlabel('Restframe V-J [Mag]')
    plt.ylabel('Restframe U-V [Mag]')
    plt.title('UVJ Diagram for the all fields')
    plt.legend()
    plt.show()


# In[128]:


plot_uvj_nocategorise(export_df, export_df['VJ'], export_df['UV'])

# Tto check the veracity of this output, we can recheck


# In[129]:


cdfs = export_df[export_df['ID'].str.contains('CDFS_16807')]


# In[130]:


cdfs


# In[131]:


# For completness we can read in associated ZFOURGE files and plot them 
zfourge_path = 'datasets/zfourge/'

# Read in ZFourge Data in each field

#CDFS, COSMOS, UDS
cdfs_df = read_zfourge_data('CDFS', zfourge_path)
cosmos_df = read_zfourge_data('COSMOS', zfourge_path)
uds_df = read_zfourge_data('UDS', zfourge_path)

# as a dataframe
cdfs_recalcUVJids = pd.read_csv('datasets/zfourge/CDFS_RecalculatedUVJids_full.csv')
cosomos_recalcUVJids = pd.read_csv('datasets/zfourge/COSMOS_RecalculatedUVJids_full.csv')
uds_recalcUVJids = pd.read_csv('datasets/zfourge/UDS_RecalculatedUVJids_full.csv')


cdfs_recalcUVJids = cdfs_recalcUVJids.rename(columns={'ID':'id'})
cosomos_recalcUVJids = cosomos_recalcUVJids.rename(columns={'ID':'id'})
uds_recalcUVJids = uds_recalcUVJids.rename(columns={'ID':'id'})


# In[132]:


# Merge the recalculated UVJ id's with the original dataframes
cdfs_df = pd.merge(cdfs_df, cdfs_recalcUVJids, on='id')
cosmos_df = pd.merge(cosmos_df, cosomos_recalcUVJids, on='id')
uds_df = pd.merge(uds_df, uds_recalcUVJids, on='id')


# In[133]:


# Making one dataframe
frames = [cdfs_df, cosmos_df, uds_df]
zfourge_df = pd.concat(frames)


# In[134]:


zfourge_df


# In[ ]:





# In[135]:


export_df


# In[136]:


# Select subset of the zfourge_df where both id's are present
zfourge_df = zfourge_df[zfourge_df['id'].isin(export_df['ID'])]


# In[137]:


# # Choose subset with only 1 field
# zfourge_df = zfourge_df[zfourge_df['field'] == 'COSMOS']

# # Likewise for the export_df
# export_df = export_df[export_df['ID'].isin(zfourge_df['id'])]


# In[138]:


# Plot the UVJ diagram for the ZFOURGE galaxies
plot_uvj_nocategorise(zfourge_df, zfourge_df['VJ'], zfourge_df['UV'])


# In[139]:


# Plotting this using my quiescent transitions calculated from ollie's data
plot_uvj_nocategorise(export_df, export_df['VJ'], export_df['UV'])


# In[140]:


# Now plotting using my original selection of transition ID's
# using the VJ_0 and UV_0 columns
plot_uvj_nocategorise(zfourge_df, zfourge_df['VJ_0'], zfourge_df['UV_0'])


# In[141]:


# For completeness plot the redshifts I brought over from my export_df against the ones in the zfourge_df
plt.scatter(zfourge_df['zpk'], export_df['zpk'])
plt.show()


# In[142]:


y = zfourge_df[['zpk', 'id']].sort_values(by='id')



# In[143]:


x = export_df[['zpk', 'ID']].sort_values(by='ID')


# In[144]:


plt.plot(x['zpk'], y['zpk'])    # straight line indicates that all redshifts are matched
plt.show()
# plot the UV entries for each export_df and zfourge_df

# likewise for VJ, all on same graph


# In[145]:


export_df


# In[ ]:





# In[ ]:





# In[146]:


# Save and export this for comparison
# save to outputs
export_df.to_csv('outputs/cigale_colours_ids.csv', index=False)


# In[147]:


# See the names of all of the column headings in the df
best_fit_seds[0].columns


# In[148]:


# Now that we have some type of SED output, we can attempt to try to convert the CIGALE decomposed outputs#
# Begin by attempting to plot L_lambda_total in a similar manner to before 
n=0
df = best_fit_seds[n]

# Aside fom the first 3, and the last 4 columns, plot the rest wavelength against the column

# iterate throught the columns, and plot the values
plt.figure(figsize=(10, 10))
for i in range(2, len(df.columns)-6):
    plt.loglog(df['wavelength'], df[df.columns[i]], label=df.columns[i])
plt.xlabel('Wavelength (Angstroms)')
plt.ylabel('Flux')
plt.xlim(1e2, 1e8)
plt.ylim(1e-30, 1e70)
plt.title('SED of galaxies')


# Plot the legend off to the side
# Create a legend with the unique labels
plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))

plt.show()


# In[149]:


# a type 1 AGN would consist of the following components
# - AGN disk
# - maybe AGN polar dust


# Whereas a type 2 would consist of all components in varying quantities
# - AGN disk
# - AGN torus
# - AGN polar dust
# Print the column names

for col in best_fit_seds[0].columns:
    print(col)


# wavelength
# Fnu
# L_lambda_total
# stellar.old
# stellar.young
# nebular.absorption_old
# nebular.absorption_young
# nebular.lines_old
# nebular.lines_young
# nebular.continuum_old
# nebular.continuum_young
# attenuation.stellar.old
# attenuation.stellar.young
# attenuation.nebular.lines_old
# attenuation.nebular.lines_young
# attenuation.nebular.continuum_old
# attenuation.nebular.continuum_young
# dust
# agn.SKIRTOR2016_torus
# agn.SKIRTOR2016_polar_dust
# agn.SKIRTOR2016_disk
# igm
# Snu
# nuSnu
# Flambda
# lambda (Angstroms)

# In[150]:


# attempting to plot the new values

# Subsetdf of only agn components


# Plotting only the AGN components
plt.figure(figsize=(10, 10))
for i in range(3, 8):
    plt.loglog(df['wavelength'], df[df.columns[i]], label=df.columns[i])
plt.xlabel('Wavelength (Angstroms)')
plt.ylabel('Flux')
#plt.xlim(1e2, 1e8)
#plt.ylim(1e-30, 1e70)
plt.title('SED of galaxies')
plt.legend()
plt.show()


# In[151]:


# Plot just the total value of L_lambda_total

# Drop the zero values
new_df = df[df['L_lambda_total'] > 10**-7].copy()

# Create an adjust L_lambda to plot against
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total']


# Remove the young and old stellar components
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['stellar.old']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['stellar.young']


# Remove the absopriton and emission lines

# Absorption
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['nebular.absorption_old']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['nebular.absorption_young']

# Emission
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['nebular.lines_old']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['nebular.lines_young']


# Removing the dust component
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['dust']


# Removing the galactic continuum
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['nebular.continuum_old']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['nebular.continuum_young']

# Removing the attentuated components
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['attenuation.stellar.old']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['attenuation.stellar.young']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['attenuation.nebular.lines_old']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['attenuation.nebular.lines_young']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['attenuation.nebular.continuum_old']
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['attenuation.nebular.continuum_young']


# Remove the igm
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['igm']


# To ensure this is done correctly, we also are choosing to consider simply just the AGN components 
# where the the values are within a range of 10^2 - 10^7
new_df = new_df[(new_df['wavelength'] > 10**-2) & (new_df['wavelength'] < 10**7)]



# Optionally we can choose to remove certain parts of the SED, such as the dust component
# the torus component living the disk component for type 1

# Type 1
# Remove the dust component
# agn.SKIRTOR2016_polar_dust
# agn.SKIRTOR2016_disk

# Removing polar dust
new_df['L_lambda_total_decomposed_type_1'] = new_df['L_lambda_total_decomposed'] - new_df['agn.SKIRTOR2016_polar_dust']

# Removing torus
new_df['L_lambda_total_decomposed_type_1'] = new_df['L_lambda_total_decomposed_type_1'] - new_df['agn.SKIRTOR2016_torus']






# normalise the values using the integral of the total flux of the original SED
# We will use the trapezoidal rule to calculate the integral of the total flux
# We will then divide the decomposed values by this integral to normalise the values
integral_total = np.trapz(new_df['L_lambda_total'], new_df['wavelength'])
integral_decomposed = np.trapz(new_df['L_lambda_total_decomposed'], new_df['wavelength'])

# Scaling factor
#scaling_factor = integral_total/integral_decomposed

# Normalise the decomposed values
#new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] * scaling_factor



plt.figure(figsize=(10, 6))
plt.loglog(new_df['wavelength'], new_df['L_lambda_total'], label='Original')
plt.loglog(new_df['wavelength'], new_df['L_lambda_total_decomposed'], label='Decomposed - Only AGN')

# Additionally try to plot the AGN component of a type 1
plt.loglog(new_df['wavelength'], new_df['L_lambda_total_decomposed_type_1'], label='Decomposed - Type 1 AGN')

plt.xlabel('Wavelength (Angstroms)')
plt.ylabel('Flux')
plt.title('SED of galaxies')
plt.legend()
plt.show()


# So now that we have seen this we know that we can easily just calculate the the galaxy with the AGN components only. We will therefore like to take a similar approach where we choose to only consider the galaxies galactic components. 
# by considering only this, in a more rigiours way we should hopefully be able to see what a 'clean' galaxy looks like. From here, with the decomposed SED we should have two components. An AGN component, and simply a galactic component with no AGN modelled into it.
# 
# We would like to subtract the AGN from all of the galaxies, and then replot these galaxies as required in UVJ space. Let us begin by attempting to create a galaxy with only the galactic components and no AGN

# In[152]:


# Drop the zero values
new_df = df[df['L_lambda_total'] > 10**-7].copy()

# Create an adjust L_lambda to plot against
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total']


# To ensure this is done correctly, we also are choosing to consider simply just the AGN components 
# where the the values are within a range of 10^2 - 10^7
new_df = new_df[(new_df['wavelength'] > 10**-2) & (new_df['wavelength'] < 10**7)]



# We would like to remove the AGN from the galaxy if possible

# Removing polar dust
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['agn.SKIRTOR2016_polar_dust']

# Removing torus
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['agn.SKIRTOR2016_torus']

# Removing the accretion disk
new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['agn.SKIRTOR2016_disk']




# normalise the values using the integral of the total flux of the original SED
# We will use the trapezoidal rule to calculate the integral of the total flux
# We will then divide the decomposed values by this integral to normalise the values
integral_total = np.trapz(new_df['L_lambda_total'], new_df['wavelength'])
integral_decomposed = np.trapz(new_df['L_lambda_total_decomposed'], new_df['wavelength'])

# Scaling factor
scaling_factor = integral_total/integral_decomposed

# Normalise the decomposed values <- Unsure if we should be doing this, but for complenetess it may be a good idea
new_df['L_lambda_total_decomposed_Scaled'] = new_df['L_lambda_total_decomposed'] * scaling_factor




plt.figure(figsize=(10, 6))
plt.loglog(new_df['wavelength'], new_df['L_lambda_total'], label='Original')
plt.loglog(new_df['wavelength'], new_df['L_lambda_total_decomposed'], label='Decomposed - No AGN')
plt.loglog(new_df['wavelength'], new_df['L_lambda_total_decomposed_Scaled'], label='Decomposed - No AGN (Scaled)')

plt.xlabel('Wavelength (Angstroms)')
plt.ylabel('Flux')
plt.title('SED of galaxies')
plt.legend()
plt.show()


# In[153]:


# Now that we have the general idea of how to decompose the SEDs, we can attempt to do this for all of the galaxies
# in the best_fit_seds list
# We will create a function that will do this for us

def decompose_agn_seds(best_fit_seds):
    # Create a list to store the decomposed SEDs
    decomposed_seds = []
    
    # Iterate through the best_fit_seds
    for i in range(len(best_fit_seds)):
        new_df = best_fit_seds[i].copy()
        
        # Drop the zero values - maybe include this potentially
       # new_df = df[df['L_lambda_total'] > 10**-7].copy()

        # AGN components - Remove the galaxy component
        # Create an adjust L_lambda to plot against
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total']

        # Remove the young and old stellar components
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['stellar.old']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['stellar.young']


        # Remove the absopriton and emission lines

        # Absorption
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['nebular.absorption_old']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['nebular.absorption_young']

        # Emission
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['nebular.lines_old']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['nebular.lines_young']


        # Removing the dust component
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['dust']


        # Removing the galactic continuum
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['nebular.continuum_old']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['nebular.continuum_young']

        # Removing the attentuated components
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['attenuation.stellar.old']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['attenuation.stellar.young']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['attenuation.nebular.lines_old']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['attenuation.nebular.lines_young']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['attenuation.nebular.continuum_old']
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['attenuation.nebular.continuum_young']


        # Remove the igm
        new_df['L_lambda_total_decomposed_AGN'] = new_df['L_lambda_total_decomposed_AGN'] - new_df['igm']
        
        integral_total = np.trapz(new_df['L_lambda_total'], new_df['wavelength'])
        integral_decomposed = np.trapz(new_df['L_lambda_total_decomposed_AGN'], new_df['wavelength'])

        # Scaling factor
        scaling_factor = integral_total/integral_decomposed

        # Normalise the decomposed values <- Unsure if we should be doing this, but for complenetess it may be a good idea
        new_df['L_lambda_total_decomposed_AGN_Scaled'] = new_df['L_lambda_total_decomposed_AGN'] * scaling_factor
        
        

        # Galaxy component - Remove the AGN Component
        # Create an adjust L_lambda to plot against
        new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total']

        # To ensure this is done correctly, we also are choosing to consider simply just the AGN components 
        # where the the values are within a range of 10^2 - 10^7
        new_df = new_df[(new_df['wavelength'] > 10**-2) & (new_df['wavelength'] < 10**7)]

        # We would like to remove the AGN from the galaxy if possible

        # Removing polar dust
        new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['agn.SKIRTOR2016_polar_dust']

        # Removing torus
        new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['agn.SKIRTOR2016_torus']

        # Removing the accretion disk
        new_df['L_lambda_total_decomposed'] = new_df['L_lambda_total_decomposed'] - new_df['agn.SKIRTOR2016_disk']

        # normalise the values using the integral of the total flux of the original SED
        # We will use the trapezoidal rule to calculate the integral of the total flux
        # We will then divide the decomposed values by this integral to normalise the values
        integral_total = np.trapz(new_df['L_lambda_total'], new_df['wavelength'])
        integral_decomposed = np.trapz(new_df['L_lambda_total_decomposed'], new_df['wavelength'])

        # Scaling factor
        scaling_factor = integral_total/integral_decomposed

        # Normalise the decomposed values <- Unsure if we should be doing this, but for complenetess it may be a good idea
        new_df['L_lambda_total_decomposed_Scaled'] = new_df['L_lambda_total_decomposed'] * scaling_factor
        
        decomposed_seds.append(new_df)
        
    return decomposed_seds 



    


# In[154]:


decomposed_seds = decompose_agn_seds(best_fit_seds)


# In[155]:


decomposed_seds[0]


# In[156]:


# plotting the first decomposed SED
plt.figure(figsize=(10, 6))



# original sed
plt.loglog(decomposed_seds[0]['wavelength'], decomposed_seds[0]['L_lambda_total'], label='Original')

# Decomposed SED - Galaxy Components 
#plt.loglog(decomposed_seds[0]['wavelength'], decomposed_seds[0]['L_lambda_total_decomposed'], label='Decomposed - No AGN')
#plt.loglog(decomposed_seds[0]['wavelength'], decomposed_seds[0]['L_lambda_total_decomposed_Scaled'], label='Decomposed - No AGN (Scaled)')

# Decomposed SED - AGN Components
plt.loglog(decomposed_seds[0]['wavelength'], decomposed_seds[0]['L_lambda_total_decomposed_AGN'], label='Decomposed - AGN')
plt.loglog(decomposed_seds[0]['wavelength'], decomposed_seds[0]['L_lambda_total_decomposed_AGN_Scaled'], label='Decomposed - AGN (Scaled)')



plt.xlabel('Wavelength (Angstroms)')
plt.ylabel('Flux')
plt.title('SED of galaxies')



plt.legend()
plt.show()


# In[157]:


# Finally we can plot our original uvj diagram with l_lambda to see the uvj results
# Doing a quick plot of the original UVJ colour space using the undecomposed SED
uv_galaxy_colours = []
vj_galaxy_colours = []
uv_full_colours = []
vj_full_colours = []

for sed_data in decomposed_seds:
    
    # Create an SED object using astSED - for the decomposed galaxy component
    wl = sed_data['lambda (Angstroms)']
    fl = sed_data['L_lambda_total_decomposed']
    sed = astSED.SED(wavelength=wl, flux=fl, z=0.0)    
    
    # create the uv and vj colours
    uv = astSED.SED.calcColour(sed, pb_U, pb_V, magType='AB')
    vj = astSED.SED.calcColour(sed, pb_V, pb_J, magType='AB')
    
    # Append colours to list
    uv_galaxy_colours.append(uv)
    vj_galaxy_colours.append(vj)
    
    # Create an SED object using astSED - for full colours 
    wl = sed_data['lambda (Angstroms)']
    fl = sed_data['L_lambda_total']
    sed = astSED.SED(wavelength=wl, flux=fl, z=0.0)    
    
    # create the uv and vj colours
    uv = astSED.SED.calcColour(sed, pb_U, pb_V, magType='AB')
    vj = astSED.SED.calcColour(sed, pb_V, pb_J, magType='AB')
    
    # Append colours to list
    uv_full_colours.append(uv)
    vj_full_colours.append(vj)


# In[158]:


uv_galaxy_colours


# In[159]:


# Plotting this in UVJ
plt.figure(figsize=(6, 6))

xmax = 2.2
ymax = 2.5
xmin = -0.5
ymin = 0



# Set the plotting limits
plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)





# Define the points for a quiescent galaxy selection
x_points = [-0.5, 0.85, 1.6, 1.6]
y_points = [1.3, 1.3, 1.95, 2.5]
# Plot the points
plt.plot(x_points, y_points, linestyle='-')

# as all the points have associated names, plot the names
#for i, txt in enumerate(df['ID']):
#    plt.annotate(txt, (x[i], y[i]))
    
# plot the points
plt.scatter(vj_galaxy_colours, uv_galaxy_colours, s=3, alpha=0.5, label='All Galaxies')

# Interpolate the y-value at x=1.2
x_target = 1.2
y_target = np.interp(x_target, x_points, y_points)

# Plot the interpolated point, this separates everything on the right as dusty galaxies,
# and everything on the left as star-forming galaxies
plt.plot([x_target, x_target], [0, y_target], linestyle='--')

plt.xlabel('Restframe V-J [Mag]')
plt.ylabel('Restframe U-V [Mag]')
plt.title('UVJ Diagram for the all fields')
plt.show()


# In[160]:


# Check for both sets of colours



plt.figure(figsize=(6, 6))

xmax = 2.2
ymax = 2.5
xmin = -0.5
ymin = 0



# Set the plotting limits
plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)





# Define the points for a quiescent galaxy selection
x_points = [-0.5, 0.85, 1.6, 1.6]
y_points = [1.3, 1.3, 1.95, 2.5]
# Plot the points
plt.plot(x_points, y_points, linestyle='-')

# as all the points have associated names, plot the names
#for i, txt in enumerate(df['ID']):
#    plt.annotate(txt, (x[i], y[i]))
    
# plot the points
plt.scatter(vj_full_colours, uv_full_colours, s=3, alpha=0.5, label='All Galaxies')

# Interpolate the y-value at x=1.2
x_target = 1.2
y_target = np.interp(x_target, x_points, y_points)

# Plot the interpolated point, this separates everything on the right as dusty galaxies,
# and everything on the left as star-forming galaxies
plt.plot([x_target, x_target], [0, y_target], linestyle='--')

plt.xlabel('Restframe V-J [Mag]')
plt.ylabel('Restframe U-V [Mag]')
plt.title('UVJ Diagram for the all fields')
plt.show()


# In[161]:


# PLot the other one without limits
# Plotting this in UVJ
plt.figure(figsize=(6, 6))

xmax = 2.2
ymax = 2.5
xmin = -0.5
ymin = 0


# Set the plotting limits
plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)





# Define the points for a quiescent galaxy selection
x_points = [-0.5, 0.85, 1.6, 1.6]
y_points = [1.3, 1.3, 1.95, 2.5]
# Plot the points
plt.plot(x_points, y_points, linestyle='-')

# as all the points have associated names, plot the names
#for i, txt in enumerate(df['ID']):
#    plt.annotate(txt, (x[i], y[i]))
    
# plot the points
plt.scatter(vj_full_colours, uv_full_colours, s=3, alpha=0.5, label='All Galaxies')

plt.scatter(vj_galaxy_colours, uv_galaxy_colours, s=3, alpha=0.5, label='AGN Galaxies')

# Interpolate the y-value at x=1.2
x_target = 1.2
y_target = np.interp(x_target, x_points, y_points)

# Plot the interpolated point, this separates everything on the right as dusty galaxies,
# and everything on the left as star-forming galaxies
plt.plot([x_target, x_target], [0, y_target], linestyle='--')

plt.xlabel('Restframe V-J [Mag]')
plt.ylabel('Restframe U-V [Mag]')
plt.title('UVJ Diagram for the all fields')
plt.show()


# In[162]:


# We would like to draw an arrow for each entry, and see where the arrow is pointing
# we would like the arrow to go from the full galaxy to the decomposed galaxy i.e full colours to galaxy only colours

# we will use the two sets of uvj colours to plot the arrows
# then plotting on a uvj diagram
# Plotting this in UVJ
plt.figure(figsize=(6, 6))

xmax = 2.2
ymax = 2.5
xmin = -0.5
ymin = 0


# Set the plotting limits
plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)





# Define the points for a quiescent galaxy selection
x_points = [-0.5, 0.85, 1.6, 1.6]
y_points = [1.3, 1.3, 1.95, 2.5]
# Plot the points
plt.plot(x_points, y_points, linestyle='-')

# as all the points have associated names, plot the names
#for i, txt in enumerate(df['ID']):
#    plt.annotate(txt, (x[i], y[i]))
    
# plot the points
plt.scatter(vj_full_colours, uv_full_colours, s=3, alpha=0.5, label='Galaxies (with AGN)')

plt.scatter(vj_galaxy_colours, uv_galaxy_colours, s=3, alpha=0.5, label='Galaxies (No AGN)')


# Adding an arrow from the full galaxy to the decomposed galaxy
for i in range(len(vj_full_colours)): 
    plt.arrow(vj_full_colours[i], uv_full_colours[i], vj_galaxy_colours[i] - vj_full_colours[i], uv_galaxy_colours[i] - uv_full_colours[i], head_width=0.025, head_length=0.05, fc='k', ec='k')


# Interpolate the y-value at x=1.2
x_target = 1.2
y_target = np.interp(x_target, x_points, y_points)

# Plot the interpolated point, this separates everything on the right as dusty galaxies,
# and everything on the left as star-forming galaxies
plt.plot([x_target, x_target], [0, y_target], linestyle='--')

plt.xlabel('Restframe V-J [Mag]')
plt.ylabel('Restframe U-V [Mag]')
plt.title('UVJ Diagram for the all fields')
plt.legend()
plt.show()


# In[163]:


plt.figure(figsize=(6, 6))

xmax = 2.2
ymax = 2.5
xmin = -0.5
ymin = 0


# Set the plotting limits
plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)





# Define the points for a quiescent galaxy selection
x_points = [-0.5, 0.85, 1.6, 1.6]
y_points = [1.3, 1.3, 1.95, 2.5]
# Plot the points
plt.plot(x_points, y_points, linestyle='-')

# as all the points have associated names, plot the names
#for i, txt in enumerate(df['ID']):
#    plt.annotate(txt, (x[i], y[i]))
    
# plot the points
plt.scatter(vj_full_colours, uv_full_colours, s=3, alpha=0.5, label='Galaxies (with AGN)')

plt.scatter(vj_galaxy_colours, uv_galaxy_colours, s=3, alpha=0.5, label='Galaxies (No AGN)')


# Instead of plotting all arrows, define an average arrow 
# we want to get the average location of each set of points, and plot the transition

# Get the average location of each set of points
avg_vj_full = np.mean(vj_full_colours)
avg_uv_full = np.mean(uv_full_colours)

avg_vj_galaxy = np.mean(vj_galaxy_colours)
avg_uv_galaxy = np.mean(uv_galaxy_colours)

# Plot the average arrow
plt.arrow(avg_vj_full, avg_uv_full, avg_vj_galaxy - avg_vj_full, avg_uv_galaxy - avg_uv_full, head_width=0.025, head_length=0.05, fc='k', ec='k')



# Interpolate the y-value at x=1.2
x_target = 1.2
y_target = np.interp(x_target, x_points, y_points)

# Plot the interpolated point, this separates everything on the right as dusty galaxies,
# and everything on the left as star-forming galaxies
plt.plot([x_target, x_target], [0, y_target], linestyle='--')

plt.xlabel('Restframe V-J [Mag]')
plt.ylabel('Restframe U-V [Mag]')
plt.title('UVJ Diagram for the all fields')
plt.legend()
plt.show()


# In[164]:


# we want to know what the average arrow size is, that is the average transition from full agn+galaxy to just galaxy
# in this sense we would like to calculate the vector from every galaxy to every decomposed galaxy
# then get simply the magnitude of that change, and average it

# we will use the two sets of UVJ colours to find this
sum_total = 0
no_agn_index = []
for i in range(len(vj_full_colours)): 
    #print(np.sqrt((vj_full_colours[i] - vj_galaxy_colours[i])**2 + (uv_full_colours[i] - uv_galaxy_colours[i])**2)) # get the magnitude of the vector
    
    # If no change occurs we assume that there was no AGN present as the colours should change
    # remove the zero values
    if np.sqrt((vj_full_colours[i] - vj_galaxy_colours[i])**2 + (uv_full_colours[i] - uv_galaxy_colours[i])**2) == 0:
        print(i)
        print('No AGN present')
        
        sum_total+=1
        
        # append the index 
        no_agn_index.append(i)
        # 
        
print("There are exactly {} galaxies where no AGN is present (assumed from no change in UVJ colour)".format(sum_total))

# Removing the values where no AGN is present
vj_full_colours_corrected = np.delete(vj_full_colours, no_agn_index)
uv_full_colours_corrected = np.delete(uv_full_colours, no_agn_index)
vj_galaxy_colours_corrected = np.delete(vj_galaxy_colours, no_agn_index)
uv_galaxy_colours_corrected = np.delete(uv_galaxy_colours, no_agn_index)
gal_names_corrected = np.delete(names, no_agn_index)

# Similarly we are dealing with the decomposed SEDs, which can be identified by an index value in names
# we would like to remove these values as well



# In[165]:


# We now plot our corrected UVJ where the AGN is present, and subsequently removed
plt.figure(figsize=(6, 6))

xmax = 2.2
ymax = 2.5
xmin = -0.5
ymin = 0


# Set the plotting limits
plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)





# Define the points for a quiescent galaxy selection
x_points = [-0.5, 0.85, 1.6, 1.6]
y_points = [1.3, 1.3, 1.95, 2.5]
# Plot the points
plt.plot(x_points, y_points, linestyle='-')

# as all the points have associated names, plot the names
#for i, txt in enumerate(df['ID']):
#    plt.annotate(txt, (x[i], y[i]))
    
# plot the points
plt.scatter(vj_full_colours_corrected, uv_full_colours_corrected, s=3, alpha=0.5, label='Galaxies (with AGN)')

plt.scatter(vj_galaxy_colours_corrected, uv_galaxy_colours_corrected, s=3, alpha=0.5, label='Galaxies (No AGN)')


# Instead of plotting all arrows, define an average arrow 
# we want to get the average location of each set of points, and plot the transition

# Get the average location of each set of points
avg_vj_full = np.mean(vj_full_colours_corrected)
avg_uv_full = np.mean(uv_full_colours_corrected)

avg_vj_galaxy = np.mean(vj_galaxy_colours_corrected)
avg_uv_galaxy = np.mean(uv_galaxy_colours_corrected)

# Plot the average arrow
plt.arrow(avg_vj_full, avg_uv_full, avg_vj_galaxy - avg_vj_full, avg_uv_galaxy - avg_uv_full, head_width=0.025, head_length=0.05, fc='k', ec='k')



# Interpolate the y-value at x=1.2
x_target = 1.2
y_target = np.interp(x_target, x_points, y_points)

# Plot the interpolated point, this separates everything on the right as dusty galaxies,
# and everything on the left as star-forming galaxies
plt.plot([x_target, x_target], [0, y_target], linestyle='--')

plt.xlabel('Restframe V-J [Mag]')
plt.ylabel('Restframe U-V [Mag]')
plt.title('UVJ Diagram for the all fields')
plt.legend()
plt.show()


# In[166]:



# Count the number of entries
len(vj_full_colours_corrected)

# Histogram of vector distance moved
plt.hist(np.sqrt((vj_full_colours_corrected - vj_galaxy_colours_corrected)**2 + (uv_full_colours_corrected - uv_galaxy_colours_corrected)**2), bins=15)
plt.title("Vector Magntiude Difference of\n UVJ colour change (AGN present to AGN removed)")
plt.xlabel("Magnitude of Vector")
plt.ylabel("Frequency")
plt.show()


# In[167]:


# Now we can recalculate the the vector differences for each of the elements
sum_total = 0
distance_moved_threshold = 0
for i in range(len(vj_full_colours_corrected)): 
    # Print only the galaxies where the distance is greater than 0.2
    if((np.sqrt((vj_full_colours_corrected[i] - vj_galaxy_colours_corrected[i])**2 + (uv_full_colours_corrected[i] - uv_galaxy_colours_corrected[i])**2)) > distance_moved_threshold):
        print("Name of galaxy: {}".format(gal_names_corrected[i]))
        print(np.sqrt((vj_full_colours_corrected[i] - vj_galaxy_colours_corrected[i])**2 + (uv_full_colours_corrected[i] - uv_galaxy_colours_corrected[i])**2)) # get the magnitude of the vector  
        sum_total+=1
print("There are exactly {} galaxies where the distance moved is greater than {}".format(sum_total, distance_moved_threshold))


# In[168]:


# To extend our idea as before we aim to classify the quiescent moving fraction. Thus we expect the quiescent galaxies to move a certain amount
# thus we will choose to exclude oterh sets of galaxies

# First we will put our galaxy with its UV, and VJ colours (both with and without)
# into a dataframe with its id. 
# Note: We are looking at only the UVJ colours where the AGN is present, and subsequently removed i.e distance moved is greater than 0

# use Gal names to get the ID
# Create a dataframe
decomposed_uvj_df = pd.DataFrame()
decomposed_uvj_df['id'] = gal_names_corrected
decomposed_uvj_df['VJ_withAGN'] = vj_full_colours_corrected
decomposed_uvj_df['UV_withAGN'] = uv_full_colours_corrected
decomposed_uvj_df['VJ_withoutAGN'] = vj_galaxy_colours_corrected
decomposed_uvj_df['UV_withoutAGN'] = uv_galaxy_colours_corrected


# In[169]:


# Using our classification code
def categorise_uvj(df, x, y, alpha=None):
    #x = df['mag_V'] - df['mag_J'] # VJ Colours 
    #y = df['mag_U'] - df['mag_V'] # UV Colours

    # Plot the UVJ diagram
    plt.figure(figsize=(6, 6))

    xmax = 2.2
    ymax = 2.5
    xmin = -0.5
    ymin = 0

    # Set the plotting limits
    plt.xlim(xmin, xmax)
    plt.ylim(ymin, ymax)

    # Define the points for a quiescent galaxy selection
    x_points = [-0.5, 0.85, 1.6, 1.6]
    y_points = [1.3, 1.3, 1.95, 2.5]

    # Plot the points
    plt.plot(x_points, y_points, linestyle='-')

    # Interpolate the y-value at x=1.2
    x_target = 1.2
    y_target = np.interp(x_target, x_points, y_points)

    # Plot the interpolated point, this separates everything on the right as dusty galaxies,
    # and everything on the left as star-forming galaxies
    plt.plot([x_target, x_target], [0, y_target], linestyle='--')

    quiescent_x = [-0.5, 0.85, 1.6, 1.6, xmin, xmin]
    quiescent_y = [1.3, 1.3, 1.95, 2.5, ymax, 1.3]
    # We want to make a wedge selection for the Quiescent Selection of Galaxies
    points = np.column_stack([x, y])
    verts = np.array([quiescent_x, quiescent_y]).T
    path = mpath.Path(verts)
    
    
    # Define the path for point selection
    #selected_path = mpath.Path([(2, 3), (6, 4), (8, 2), (2, 1), (2, 3)])  # Example path, replace with your own

    # Use path.contains_points to get a boolean array
    points_inside_selection = path.contains_points(np.column_stack([x, y]))
    
    
    
    dusty_condition = (points[:, 0] > x_target) & (~points_inside_selection)
    star_forming_condition = (points[:, 0] < x_target) & (~points_inside_selection)
    
    

    # Filter the DataFrame using the boolean array
    selected_df = df[points_inside_selection] # For quiescent, clean later
    

    # Mark dusty, and star-forming galaxies
    if alpha == None:
        df.loc[dusty_condition, f'GalaxyType'] = 2
        df.loc[star_forming_condition, f'GalaxyType'] = 1
        selected_ids = selected_df['id']
        df.loc[df['id'].isin(selected_ids), f'GalaxyType'] = 0
    else:     
        df.loc[dusty_condition, f'GalaxyType_{int(alpha*100)}'] = 2
        df.loc[star_forming_condition, f'GalaxyType_{int(alpha*100)}'] = 1
        selected_ids = selected_df['id']
        df.loc[df['id'].isin(selected_ids), f'GalaxyType_{int(alpha*100)}'] = 0

    #print(selected_df)
    #print(unselected_df)
    
    # Now we can easily select the quiescent galaxies and set the galaxy type to quiescent - 0 or starforming 1.
    #print(selected_df)
     # This is what makes the selection happen
    
    
    
    # Try do the same for the unselected galaxies, noting that the unselected galaxies with x and y > 1.2 are dusty galaxies, and the rest are star-forming galaxies
    #unselected_ids = unselected_df['id']
    
    
    
    
    # Sort the quiescent and non-quiescent galaxies
    quiescent_points = points[path.contains_points(points)]
    # Find the points from here to categorise dusty, and star-forming galaxies
    non_quiescent_points = points[~path.contains_points(points)]
    dusty_galaxies_points = non_quiescent_points[non_quiescent_points[:, 0] > x_target]
    star_forming_galaxies_points = non_quiescent_points[non_quiescent_points[:, 0] < x_target]
    
    
    #print(non_quiescent_points[0][0])
    
    #print(y)
    # Plot the selected points
    #plt.scatter(x, y, s=3, alpha=0.5, label='Not Quiescent Selection')
    plt.scatter(quiescent_points[:, 0], quiescent_points[:, 1], c='r', s=3, alpha=0.5, label='Quiescent Selection')
    plt.scatter(dusty_galaxies_points[:, 0], dusty_galaxies_points[:, 1], c='g', s=3, alpha=0.5, label='Dusty Galaxies')
    plt.scatter(star_forming_galaxies_points[:, 0], star_forming_galaxies_points[:, 1], c='b', s=3, alpha=0.5, label='Star Forming Galaxies')

    plt.xlabel('Restframe V-J [Mag]')
    plt.ylabel('Restframe U-V [Mag]')
    plt.title('UVJ Diagram for the ZFourge Fields')
    plt.legend()
    plt.show()
    return df


# In[170]:


# We would like to create a classification system for the galaxies
# i.e quiescent, star-forming, dusty, etc
decomposed_uvj_df = categorise_uvj(decomposed_uvj_df, decomposed_uvj_df['VJ_withAGN'], decomposed_uvj_df['UV_withAGN'])
decomposed_uvj_df = categorise_uvj(decomposed_uvj_df, decomposed_uvj_df['VJ_withoutAGN'], decomposed_uvj_df['UV_withoutAGN'], 1)

# Rename the second GalaxyType from GalaxyType100 to GalaxyType_NoAGN
decomposed_uvj_df.rename(columns={'GalaxyType_100': 'GalaxyType_NoAGN'}, inplace=True)


# In[171]:


decomposed_uvj_df


# In[172]:


# Plot the distribution of galaxies that moved (Galaxy Type isn't equal)
# Count the number of galaxies that have moved

# Check if the galaxy type has changed
decomposed_uvj_df['GalaxyType_Changed'] = decomposed_uvj_df['GalaxyType'] != decomposed_uvj_df['GalaxyType_NoAGN']

# if it is not the same between columns, mark as changed
decomposed_uvj_df['GalaxyType_Changed'] = decomposed_uvj_df['GalaxyType_Changed'].astype(int)


# In[173]:


decomposed_uvj_df

# PLot the distribution of changes
plt.hist(decomposed_uvj_df['GalaxyType_Changed'], bins=3)
plt.show()


# In[174]:


# We would now like to plot the histrograms of the different types.

decomposed_uvj_df


# Using seaborn

# Plot the distribution of galaxies in eah type
sns.histplot(decomposed_uvj_df['GalaxyType'], bins=3, color='r', label='With AGN')
sns.histplot(decomposed_uvj_df['GalaxyType_NoAGN'], bins=3, color='b', label='Without AGN')
plt.xlabel('Galaxy Type')
plt.ylabel('Frequency')
plt.title('Distribution of Galaxy Types')
# change the name of the x axis to each galaxy type: 0 for quiescent, 1 for star-forming, 2 for dusty
plt.xticks([0, 1, 2], ['Quiescent', 'Star Forming', 'Dusty'])


plt.legend()
plt.show()


# In[175]:


# Next steps

# 1.A next step may involve quantifying by how much did these move and comparing this movement against the AGN addition metric we developed using the template sets, and ZFOURGE data from before.

# Start by selecting a subset of the data, we will just check on galaxies that after the AGN was removed are classified as quiescent

# Select the subset of the data
galaxy_subset = decomposed_uvj_df


# In[176]:


# Cehck the size of the subset
len(galaxy_subset) # Of the decomposed 


# This is a reasonable enough subset to investigate. Plot the subset
categorise_uvj(galaxy_subset, galaxy_subset['VJ_withoutAGN'], galaxy_subset['UV_withoutAGN'], 1)


# In[177]:


# Knowing this we can then plot the average distance moved by the quiescent galaxies from (full to non-agn)

# Create a metric. The distance from VJ, UV with AGN to VJ, UV without AGN
distance = np.sqrt((galaxy_subset['VJ_withAGN'] - galaxy_subset['VJ_withoutAGN'])**2 + (galaxy_subset['UV_withAGN'] - galaxy_subset['UV_withoutAGN'])**2)

# direction - we want the direction from VJ, UV with AGN pointing to VJ, UV without AGN - this is the direction of the arrow with the distance specified above
# calculate the direction
direction = np.arctan2(galaxy_subset['UV_withoutAGN'] - galaxy_subset['UV_withAGN'], galaxy_subset['VJ_withoutAGN'] - galaxy_subset['VJ_withAGN'])


# In[178]:


galaxy_subset['vector_magnitude'] = distance
galaxy_subset['vector_direction'] = direction


# In[179]:


galaxy_subset


# In[180]:


# plot the vector magnitude
plt.figure(figsize=(10, 10))
plt.hist(galaxy_subset['vector_magnitude'], bins=20)
plt.xticks(np.arange(0, 0.35, 0.02))
plt.title('Distance moved by Galaxies after AGN Removal')
plt.xlabel('Vector Magnitude')
plt.ylabel('Frequency')
plt.show()


# In[181]:


# Futher reduce the fraction by limiting an AGN fraction of less than 0.02
# Select the subset of the data
galaxy_subset = galaxy_subset[galaxy_subset['vector_magnitude'] > 0.02]


# In[182]:


galaxy_subset


# In[183]:


# Plotting the UVJ diagram with the vector magnitude arrows 
# Set the plotting limits
plt.figure(figsize=(6, 6))

plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)


# Plotting our with AGN points, and without
plt.plot(galaxy_subset['VJ_withAGN'], galaxy_subset['UV_withAGN'], 'r.', label='With AGN')
plt.plot(galaxy_subset['VJ_withoutAGN'], galaxy_subset['UV_withoutAGN'], 'b.', label='Without AGN')



# Somewhere on the graph plot the average arrow
# average arrow
average_distance = np.mean(galaxy_subset['vector_magnitude'])

# average direction
average_direction = np.mean(galaxy_subset['vector_direction'])

# plot an arrow on the graph at some point 
plt.arrow(1, 1, average_distance*np.cos(average_direction), average_distance*np.sin(average_direction), head_width=0.025, head_length=0.05, fc='k', ec='k')


# plot all distance and direction arrow for all points
for i in range(len(galaxy_subset)):
    plt.arrow(galaxy_subset['VJ_withAGN'].iloc[i], galaxy_subset['UV_withAGN'].iloc[i], galaxy_subset['vector_magnitude'].iloc[i]*np.cos(galaxy_subset['vector_direction'].iloc[i]), galaxy_subset['vector_magnitude'].iloc[i]*np.sin(galaxy_subset['vector_direction'].iloc[i]), head_width=0.025, head_length=0.05, fc='k', ec='k')


# Define the points for a quiescent galaxy selection
x_points = [-0.5, 0.85, 1.6, 1.6]
y_points = [1.3, 1.3, 1.95, 2.5]

# Plot the points
plt.plot(x_points, y_points, linestyle='-')

# Interpolate the y-value at x=1.2
x_target = 1.2
y_target = np.interp(x_target, x_points, y_points)

# Plot the interpolated point, this separates everything on the right as dusty galaxies,
# and everything on the left as star-forming galaxies
plt.plot([x_target, x_target], [0, y_target], linestyle='--')

quiescent_x = [-0.5, 0.85, 1.6, 1.6, xmin, xmin]
quiescent_y = [1.3, 1.3, 1.95, 2.5, ymax, 1.3]



plt.xlabel('Restframe V-J [Mag]')
plt.ylabel('Restframe U-V [Mag]')
plt.title('UVJ Diagram for the ZFourge Fields')
plt.legend()
plt.show()


# In[184]:


# Previously we compared the amount of AGN added to any galaxy, and how far it moved given a particular percentage of AGN added
# We would like to compare this to the distance moved by the quiescent galaxies and try to backtrack and determine the percentage of AGN
# based on the distance it moved in UVJ colourspace.


# In[185]:


# Select a subset again of our subset and investigsate the individual contributions
# Select the subset of the data
galaxy_subset


# In[186]:


# output the data to a csv file, adding a new column that adds a field column by splitting the id into field + number
galaxy_subset['field'] = galaxy_subset['id'].str.split('_').str[0].copy()


# In[187]:


galaxy_subset


# In[188]:


# Save
galaxy_subset.to_csv('Decomposed_UVJ_Ids.csv')


# In[ ]:


# Another thing we could do is given our selection of AGN-less galaxies, we could put these SEDs back through my code, adding the AGN component back in to see if we can recreate at what point is the AGN component matching the observed SEDs
# At this point, this should tell us our AGN fraction (alpha value)

# So we have a selection of galaxies that don't contain any AGN. 
# So for each of the generated SEDs. Take that SED, an export it to a CSV file. so we can use our previous method of AGN addition 
# to put the AGN back in, and to try to infer the alpha value



# We only need the subset of ID's




